### ISSUE TITLE
errors with the mdsn when module is used

### ISSUE THREAD

**Issue by KingCheng1987** [watson/airplay-server#4]
I did the test with the api followed:

var server = require('airplay-server')("my pc airplay");

server.on('request',function(req,res){
    console.log("aiplay request",res);
});

server.listen(6000);

but, when the test actived,the errors came followed:
module.js:339
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/king/re/node_modules/airplay-mdns- server/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

what can i do to fix the error?

**Comment by watson** [comment]
What operation system are you running on? Seems like it can't find the dns bindings

**Comment by buzai** [comment]
Error: Cannot find module '..\build\Release\dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\airp
npminstall\mdns\2.3.3\mdns\lib\dns_sd.js:32:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

it is win7 ,it is same error ,how can fix it.

**Comment by KingCheng1987** [comment]
I updated  my nodejs,then the problem disappeared.But i  forgot the special situation,if I don't misremember ,my nodejs is not match with the package.json

**Comment by KingCheng1987** [comment]
I forgot  my special situation, if i didn't misremember,my nodejs version didn't meet the package.json

**Comment by simkuns** [comment]
@buzai 


> 
> 
> Error: Cannot find module '..\build\Release\dns_sd_bindings'
> at Function.Module._resolveFilename (module.js:339:15)
> at Function.Module._load (module.js:290:25)
> at Module.require (module.js:367:17)
> at require (internal/module.js:16:19)
> at Object. (C:\Users\Administrator\Desktop\airp
> npminstall\mdns\2.3.3\mdns\lib\dns_sd.js:32:22)
> at Module._compile (module.js:413:34)
> at Object.Module._extensions..js (module.js:422:10)
> at Module.load (module.js:357:32)
> at Function.Module._load (module.js:314:12)
> at Module.require (module.js:367:17)
> 
> it is win7 ,it is same error ,how can fix it.

I was facing the same issue, however, downloading and installing Bonjour SDK fixed it

Bonjour SDK will create system environment variable BONJOUR_SDK_HOME which points to installation dir
